markdown: kramdown
highligher: rouge

permalink: /:categories/:title/
baseurl: /Onderwis-en-Communicatie

title: "Onderwijs en Communicatie"
subtitle: "University of Amsterdam"

Projects:
  week1: Week 1
  week2: Week 2
  week3: Week 3
  week4: Week 4
  extra1: Extra

kramdown:
  parse_block_html: true
